### ISSUE TITLE
Question regarding AM and RM bombs/missiles

### ISSUE THREAD

**Issue by SupernovaCo** [aidancbrady/DefenseTech#13]
Just wondering, what recipes will you use for the Antimatter and Red Matter bombs, since Atomic Science is no longer updated? Are you going to remake the particle accelerator system by any chance?

Also, on a mostly unrelated note, do you plan to add any new bombs/missiles (following the same general theme as the originals)?

**Comment by aidancbrady** [comment]
I'm planning on adding some kind of end-game machinery to Mekanism that will provide the resources necessary to produce T4 weaponry.

And yes, new missiles are planned :)
