### ISSUE TITLE
Crash when accessing radar station

### ISSUE THREAD

**Issue by superpie43** [aidancbrady/DefenseTech#20]
Whenever accessing the radar station, my game will crash with an index out of bounds exception. Here is the full report.

[crash-2016-05-04_13.00.18-client.txt](https://github.com/aidancbrady/DefenseTech/files/249225/crash-2016-05-04_13.00.18-client.txt)

**Comment by superpie43** [comment]
the crash happens in any gui, I just got it once again when using the launcher platform.

**Comment by aidancbrady** [comment]
I can't reproduce this with the latest version.
