### ISSUE TITLE
Antimatter explosion doesn't break Mekanism cables

### ISSUE THREAD

**Issue by xerillum** [aidancbrady/DefenseTech#21]
Antimatter explosions don't break Mekanism cables and gas/liquid/item tubes. This affects all four tiers of cable, and this happens with both the missile and the separate explosive block. Other explosions (tested with DT nuclear explosives)  still break the cables, so this doesn't look like intended behavior.

![2016-05-06_13 09 05](https://cloud.githubusercontent.com/assets/6325075/15082136/c4c89f38-138b-11e6-9db9-7469df600563.png)

**Comment by aidancbrady** [comment]
Fixed! Thanks.
