### ISSUE TITLE
Issue with MineTweaker

### ISSUE THREAD

**Issue by RedGuy54** [aidancbrady/DefenseTech#25]
As you said on Reddit, the recipes for DefenseTech are temporary, so I took it upon myself to change some of them. One issue I ran into was with the launcher support frame. Since all 3 tiers have the exact same data value, I couldn't get it to work with MineTweaker. I tried customizing the name of the support column in MineTweaker, but it still acted as tier 1. There might be another way to get around this, but I haven't found it. But either way, I think they should have separate data values.

**Comment by TerdyTheTerd** [comment]
The only way I found to change the recipes it to remove them first, then add back each one, even if you don't change one you have to add it back with its metadata or it will just copy the other one. Here is a basic example with Tier 1 using Copper ingots, Tier 2 using Iron, and Tier 3 using Gold. http://pastebin.com/eVndNTMz

**Comment by RedGuy54** [comment]
@TerdyTheTerd Sorry for late response. This works perfectly, thank you.
