### ISSUE TITLE
Nuclear Explosives producing Mycelium

### ISSUE THREAD

**Issue by Twilix01** [aidancbrady/DefenseTech#26]
I strongly remember in the original ICBM nuclear explosives produced nuclear waste blocks and a toxic waste fluid, which is part of what made these explosives so dangerous, but in the current version of DefenseTech the nukes produce mycelium blocks instead. I remember this being something that eventually happened to ICBM in it's later versions but it was never addressed that I can remember.

**Comment by aidancbrady** [comment]
Mycelium is used as the temporary radioactive block- I'm planning on replacing it once I have time. In the meantime, just pretend :)

**Comment by Twilix01** [comment]
Ah, okay, that's understandable then. Thank you for the quick response!
