### ISSUE TITLE
Explosions block break event & RF Tools

### ISSUE THREAD

**Issue by bigtiger88** [aidancbrady/DefenseTech#27]
The explosives, even as small as a condensed explosive, seem to break block protected through RF Tools. These include the RF Tools block protector, and the RF Tools Shield Projector. For example, the Block Protector is configured to stop explosions from breaking a block, lets say a block of iron. If you set off any explosion from this mod, the block still breaks, where vanilla explosions do not. As for the Shield Projector, the Shield Template Blocks are protected from explosion, but any block inside the shield is still broken. Additional, the EMP explosive does not effect blocks inside the RF Tools Shield, where you would expect something like an EMP to be purposefully made to do that.

Not sure if this is on the DefenseTech or RF Tools side of things, but I reached out to @mcjty on twitter. See conversation and videos below:

https://twitter.com/MattieDaddy/status/733912958930161664

https://www.youtube.com/watch?v=pvn1cC5TTUs

https://www.youtube.com/watch?v=7gabkwe_6jA

**Comment by aidancbrady** [comment]
Merging with #45
