### ISSUE TITLE
[Feature Request]  Power Armour? 

### ISSUE THREAD

**Issue by blockaxe333** [aidancbrady/DefenseTech#30]
So ive got a couple of content idea's that i want to throw out into the open, which could be individual modules or just new parts of the mod to expand on it, which ill list below. 

Note : Ive had little experience with the new incarnation of the mod, due to implementation difficulty, so excuse me if i make references to concepts or systems outdated by the reboot , danke :3 

[ Power Armour ] 

I'm not talking like the traditional Numina-powered suits of Armour, more like Edge of tomorrow or Elysium exo-suits , with as cool models as possible that would add more of a infantry-based side of defense or offense for players, which i think is a cool idea because the majority of defense tech and its predecessor's content is in majority, static base-designed defenses and offenses.  The actual technology to build this would require processes from mekanism to manufacture i'm sure, and would be in majority manufactured from steel for the majority of the parts, with some form of circuitry to complement it. 

note: the suit's once built would be held in a "suit rack " similar to iron man's gear, and displayed similarly , this plays into some of the attachments and would have ports on the sides for oxygen , and power to be pumped in. Similar to Fallout 4's power armour rack , from here the suit can be modified as required , as long as its powered ( under the assumption the rack inserts the modules for you ) 

note : Some upgrades are "internal" and make no physical difference on the suit, but major upgrades like batteries, or power swords or certain helmet upgrades would change aspects of the physical suit model. 

note : when a suit runs out of durability all of its attachments bar plating are rendered useless, slowness is applied to the player plus blindness if an enclosed helmet is installed. They can be repaired with a shapeless recipe including each part, circuitry , steel and whatever other elements deemed necessary. Note-Note : Or they could be placed in the armor rack and auto-repaired for a chunk of power? 
Attachments :  
- portable radar add-on, similar to the Aliens universe motion detector for mobs and players but also detects in coming missiles, or EMP towers if upgraded. 

- Agility boosters , attachments added to the leg section of the suit which allow a 'step-up' bonus or increased speed, jumping etc 

- strength boosters , attachments to the torso which increase the physical strength of the wearer to the point where he/she can break blocks below diamond level with ease and gains a permanent powered knock-back bonus. 

- Uni-Wrench add-on, a wrench attachable to the torso section that has cross-mod capability. 

- Missile commander , a helmet and torso attachment set that allow's - when used with the portable radar to use missile strikes from a pre-determined launcher in a manner similar to 'Call of Duty's' predator missiles. 

- Various Batteries , a set of tiered batteries powering the above and below sets of attachments. 

- Exo-doc , a built in but invasive ( permanent reduction of health by a heart? ) medical assistant whom automatically heals the user and can be upgraded for faster speed of healing in one or more tiers. 

- Armour plating , fairly simple but increases both  the durability of the exo-suit and the wearer, with dampening upgrades to increase the user's health by a few hearts whilst wearing the suit. 

- Auto-caller, a radio transceiver hooked into the Suit's stationary rack that automatically call's the suit to the wearer and attach's itself in place of whatever armor the user is currently wearing ( forces armor into inventory or ground , and may require chunk loading capability. ) 

- Ferro-magnets , a set of magnet's attached to the leg's and boots that allow anything not bolted down to be drawn towards the player. 

- weighted boots , a set of boots which allow the player to walk along the bottom of the ocean unhindered. 

- Oxygen supply , a tank of oxygen equipped to the torso with respective breathing apparatus's equipped to the helmet that allow breathing in vacuum's or under-water provided oxygen is given.

- "Venom Drones" , minute robot's launch-able similar to an ender pearl that can attach to walls, roofs or the floor ( adding blocks that prevent this? ) , which can be used as remote camera's. 

- "Venom Uplink" , an interface with customization placement on the HUD that allows remote viewing and cycling through view's of " Venom Drones " ( looking-glass API ) 

- Power sword , an automated hydraulic attachment with swords that allow the use of a normal sword in a manner similar to a bayonet but with increased puncture damage due to piston-powered pushes. attached on torso

- Enclosed helmet ( original helmet is like a frame ) , a set of metal plates shaped to spec that allow the cosmetic closing of a suit, but to little functional change bar possible increase in durability and damage reduction. 

- Engineers wrench , not an attachment but a powered multi-tool that allow's the changing of attachments in the field, so long as its powered and with a cool down/ installation time per 
attachment. 

- E.W.P , the Emergency Wind-up Power-supply is an attachment to the torso and leg's which either allow's a player to click and generate a set ( but minute ) portion of energy per click, or to walk / run and generate an even smaller amount of energy per block moved. 

- Pheromone generator , a capsule attached to the helmet which makes the player "invisible" to mobs which are hostile. 

- Enclosed suit , similar to the enclosed helmet plating this attachment cover's the respective torso, legs and boots in metal plating , although its unsealed for a moderately increased durability of the suit. 

- Reflective plating , an upgraded enclosed suit, this system incorporates several layers of silver and glass in a lacquered "plate" which can reflect high-energy lasers and energy-based weapons. 

- Ablative plating , an alternative upgraded enclosed suit , this system encorporates micro-plates of high-density metal , which when linked together sacrifice increments of durability in chunks to prevent damage from shrapnel, explosives or other ballistic dangers. 

- Hazmat plating,  an upgraded enclosed suit that includes biological seals , this system incorporates hazmat-grade seal's made out of rubber and steel wire underneath thicker-cut metal plating , which prevents external potion effect's( negative or positive )  , radiation and fire( at the rapid cost of durability. ) 

- Shoulder mount , a socket attached to the torso which allow's further mounting of weapon systems. 

   - Rail gun , a militarized array of magnets that launches ballistic rounds at high speeds - must be 
             powered. 
   - Missile launcher, fires lower powered missiles once loaded towards a manually aimed target or 
     used in sync with the missile commander attachment to fire missiles towards remote targets.
    -     auto loader, an attachment to the back of the of the torso which auto-load's ammunition from  
           an internal reservoir into weapons systems, not powered. 
   -  Shock dampeners , these allow higher powered missiles ( mid tier ) to be fired from the suit. 

- Improved servo's , high-power magnet array's replace traditional hydraulic array's in the leg's and arm's, increasing speed , strength etc but also allow vertical scaling of surfaces. 

- Battlefield power jack , this baby allows the player , when interfacing with any machines to input a set portion of power into their suit or to output a certain portion of power to any machines when shift-clicked. 
     Note : this would be done with a GUI that has sliders etc 

Defensive technologies and Offensive technologies : 

Note that , i know there is a post request for this kind of idea already but expanding on the concept on several fronts. 

Concepts : 

Barricades :
 A multi-block item that when placed,  takes up either 2 blocks , 4 blocks , 6 blocks , 8 blocks,  9 blocks or 12 blocks in various formations dependent on the specific recipe used to craft it. 
The bonus besides blast-proofing for barricades over regular walls is that when used - they can be customized for firing or viewing ports, and my patented concept is "shared durability". Say a conventional missile incoming has the explosive output of 100 , stone has a resistance of 15 and therefore is wiped out within the explosive radius. Whereas reinforced-stone barricades share the durability across the entire barricade with all blocks, so if all the barricade blocks have a durability of 20, the durability used to calculate damage from the explosive impact is the sum of all the barricade-block's durability, so since its (9x20) the barricade would not break. This can be tiered as well. 
 Note : not vertically stackable or horizontal. 

Turrets : 
Im talking both automated and a variety of mountable turrets with a majorly limited customization ( ammunition types , barrel endings etc ). These little buddies are either used on battlefields for increased fire power against reinforced targets ( like barricades ) or defensively in bases ( automated ) as automated sentries. Similar to Open turrets or the original Voltz-era automated turrets with the bad-ass animations. The turret's themselves could be tiered like so - 

Cheap-ballistic : Fires low calibre rounds and is generally less effective all round, but made from pure iron. 

Military-ballistic : Spews out fiery hot death baby! big calibre bullets at a high rate of fire and made from denser materials with protective plates around the user. 

 Laser : This thing needs a constant power supply or a BIG battery ( like those found on high-end    exo suits? ) to power it, but spews out super-hot laser's that can melt blocks, an enemy base or the  other guys face. 

 Artillery : This thing... well lil' bessy fire's massive ballistic shell's that have a piercing capability , able to pierce the ground and "drill" , or go through multiple walls/barricades. She's expensive to build with significantly higher metal costs for the dampening, and the aiming is off since the barrel is off-set to the right of the user. 

 Rail-gun : this thing is a ramped up version of a power-suits shoulder-mounted railgun, it fires massive metal slugs at near-sonic speeds that can decimate walls , barricades or entire sides of based with outward shrapnel. 

 Environmental : Flamethrower, chemical , viral ( potion ) or a combination of the above ammunition to be used as a field-clearing or tight-corners defensive weapon. Ineffective almost entirely against heavily-armored exo suits though. 

M.V.S : Mounted Venom systems are a secured and armored version of a the drones and viewing hardware in the exo-suits. Using a security desk turned into a specified channel or need-be, specific coordinates of the camera the desk can hold up to four views from camera's.  The camera's can be individually rotated with a GUI interface along the  X , Y and Z axis with limitations surrounding the nature of their placement. 

Directed Inferno Bomb : this missile would be mid tier, and unlike incendiary or piercing explosives, it combines the two to sweep a wave of fire over a directed target, burning or scorching the surface of a base or the ground, and potentially melting rock if of a significant ordnance. 

Energy Signature Tracker : This baby can track large energy signatures, whether thermal , radioactive or electric provided all are in large quantities. In practice it's as multi block set up similar to a radar , but with a viewing GUI that show's a optionally rotatable view of the surrounding chunk-loaded area, and any large energy signatures, with Blue being electrical , red being thermal and purple being radioactive. This is particularly effective against reactors buried in bunkers, if the attackers are searching for exact coordinates to excavate or bomb. However the downside is ( you could calculate it mathematically or by chunk ) for each block ( singular block per vertical slot of 256 )and/or chunk the tracker loads, it costs a certain chunk of energy to initially scan and then later re scan. This also allows partial functionality when energy is inefficient for full scans, so battle-field placed batteries can provide enough power for a scan of the immediate area.  
  Note : it can also detect stored exo suits with significant battery storage 

"Party" missile bouncer : rather then being ablative to the explosion of a missile, this computer system hack's the targeting software in an incoming missile detected by radar and redirects it at the firing coordinates , but does not work against lowest or lower tier missiles. This requires that the missile be detected within a range of 5000 blocks , and has a hacking time of 50 seconds, and a turn around time of 5 seconds for the missile. The firing system for the missile that launched it originally will also emit either an alarm, or a warning in the local vicinity with the @player clause. 

Blast doors : Reinforced multi-block doors that are usually automatic, but can be manually opened by individuals ( clicked multiple time to open + close ) , and are created in 3 tiers of increasing hardness as per missile tiers, with each tier having significant resistances to most of the missiles in the respective tier.  
 Note : possible shared durability similar to barricades? 

the "Stark" missile : This baby has a micro reactor in its payload, and will literally decimate mountains , although to a lesser extent then more exotic payloads. It should be still considered a high tier missile for its immense destructive capabilities, with minimal fallout and minimal cleanup from a environmental standpoint. Stored "stark" 's have a radioactive signature on tracking GUI's though. 

subterranean missiles : although not strictly subterranean these class of missiles will burrow through a certain number of blocks and then strategically release its payload under ground. Several tiers would exist that dictate how many blocks the missile will burrow before engaging its payload , such as 20 blocks, 40 blocks,  80 blocks , 100 blocks, and finally 120 blocks. These would be a upper-middle tier missile. 

Sonic tripwire : unlike the game "The hidden" for some of you, this detects blocks broken by anyone other then its owner in a hollow cube or sphere of a certain radius. I.E it projects the walls , floor and roof of a cube to a certain radius from the block and will emit warnings via redstone or via proximity to the player based on whom is breaking the blocks. 

The "Ender-man" : this portable launcher fires a ender-pearl contained in a chemically fueled micro-rocket-drill, it burrows through either 3 or 5 blocks and emits the ender pearl on the other side, allowing strategic, but necessarily calculated offensive entries. 

high-density foam emitters ( possible Ic2 interaction ) ; when a payload is detected via redstone impulse or direct proximity, these emitters will spray a field  outwards of foam that dries in a matter of seconds , which can stop most if not all blasts short of a nuclear attack. 
 note : the dried blocks would require diamond tools or higher to break, and wouldn't drop anything. Also note the emitters would need some kind of fuel, or would have limited uses after crafting. Also note:note that the emitters would work similarly to the bouncer, in that it has a countdown after the missile is detected in range but a radar could emit impulses to the emitters prematurely, so the foam would be in place and hardened before the missile is in striking range. 

Satellites : Launch-able orbital systems preloaded with missiles , or later remotely loadable with payloads that would strategically launch missiles from orbit by "dropping them" requiring no set location for the missile setup , the missile can't be bounced and Exo suits with the correct frequency of the satellite could fire them from orbit to nearby locations. The orbitals can be loaded with any tier of missile but can only be later loaded with medium or low tier missiles and would incur no energy cost for firing it, however theirs a 15 minute countdown after the launch is triggered with a warning being stated in chat.  

"silver-storm" missile, this baby infests the local chunks of its target with a extremely high number of silverfish, making mining, excavation or subsequent explosions reveal a high number of silverfish - up to 6 per block. This wouldn't also affect just the surface, but several blocks deep and the faces of any subterranean cave systems. 

Thats about it for now, ill update further down with other ideas i have - but let me know what you think folks!

**Comment by blockaxe333** [comment]
have a look @aidancbrady  , @Vexatos  , @PrototypeTheta  ?

**Comment by aidancbrady** [comment]
This is something I'm considering implementing into Mekanism itself. You can see the feature request issue there.
