### ISSUE TITLE
Exiting the T1 Launcher Control Panel crashes the client

### ISSUE THREAD

**Issue by Lartza** [aidancbrady/DefenseTech#32]
https://gist.github.com/Lartza/4a71d182a93ede7cd5018f3b2b257f74

Version 1.0.1.39, SMP. Server logs don't show anything going wrong at this point.

**Comment by Lartza** [comment]
This does not seem to happen in single player.

**Comment by Lartza** [comment]
Managed to squeeze some more testing time and this seemed to happen with the T2 panel too, but apparently not the T3 panel.

**Comment by aidancbrady** [comment]
Fixed, thanks.
