### ISSUE TITLE
T2 & T3 missile recipes missing

### ISSUE THREAD

**Issue by djoveryde** [aidancbrady/DefenseTech#34]
Tier 2 & 3 missile launchers are uncraftable as they have no recipe?

**Comment by RedGuy54** [comment]
The tier 2 and 3 launcher platforms have a recipe... It might not be showing for you since all 3 of the missile launchers have the same data value, what separates them apart is NBT data. Use NEI.

**Comment by Dudoleitor** [comment]
I'm using NEI but I can't craft T2 and T3 platforms. Where can I find their recipe? I tried to use MineTweaker but it always crafts T1 only.

**Comment by PythonJellyfish** [comment]
having same issue; seems to be with NEI rather than the defensetech mod. They're all under the same ID which is the issue its having. Will download the DTDK maybe and see if i can locate the recipe and report here if i find it

**Comment by QuantumTraverse** [comment]
Furthermore, it seems that trying to craft the T2 launcher platform crafts the T1 launcher control panel instead

**Comment by QuantumTraverse** [comment]
It seems that because the different tiers are all stored under the same data value, all the other machines (like the EMP tower and the radar station) have had their recipes messed up as well

**Comment by aidancbrady** [comment]
Recipes should be better handled in the latest release.
