### ISSUE TITLE
[Feature Request] Better recipes and integration with Mekanism

### ISSUE THREAD

**Issue by Tomson124** [aidancbrady/DefenseTech#36]
You could do a lot of cool stuff with DefenseTech as it has Mekanism as a dependency.
Maybe implement the "original" way of getting anti/red matter by building an collider for elements...
But what really has to be changed are some the recipes as some explosive aren't even craftable with their current recipes.

**Comment by Andrew2070** [comment]
I changed a lot of the recipes on my own.
Made each tier harder to create as an explosive, and as missiles.

**Comment by aidancbrady** [comment]
Planned :)

**Comment by Tomson124** [comment]
Dear friend! 

This is what you were looking for, this information may  be  useful for you, read  more  at http://nkordizingu.smileranks.com/e3kguj

Best regards, tomson124

**Comment by Tomson124** [comment]
Hi, 
I know it might be  something strange, but  still so interesting, you have  to see it  here http://ltytojotho.candlsolutions.com/e3gqvaz

Cheers, timme17@t-online.de

**Comment by Tomson124** [comment]
Hello! 

I saw you last achievements, and I think you need to keep  up the good work! Here is some helpful information  for  you http://trultahyxa.groundedcomic.com/e3egd

Warmly, tomson124
