### ISSUE TITLE
[BUG] Explosion Affect

### ISSUE THREAD

**Issue by Andrew2070** [aidancbrady/DefenseTech#42]
Well its pretty self explanatory but,

When you detonate any kind of dangerous missile like a nuke or antimatter.
It will not kill you in survival mode at all. It'll do knockback but no damage to a player.

Also, can you look into adding radiation effects that are created by the blast?
Maybe even a mushroom cloud for a nuke?

**Comment by aidancbrady** [comment]
Increase the game difficulty, this is intended behavior.

Game effects have already been suggested :)
