### ISSUE TITLE
Request: Fire either an explosion or blockbreak event for explosions

### ISSUE THREAD

**Issue by DraksterAU** [aidancbrady/DefenseTech#45]
Hi @aidancbrady 
If possible, can you add a vanilla forge block break / explosion event when a missile/explosive goes off?
This way we can prevent them damaging protected areas (Similar to what you do with the Digital Miner).
Regards,
DraksterAU

**Comment by DraksterAU** [comment]
PS: If you can assist me in compiling your mod, I'll happily do a PR. I'm getting all kinds of compilation errors... what do you depend on exactly other than Mek?

**Comment by DraksterAU** [comment]
Hi @aidancbrady I've completed an API class that when registered on the minecraftforge event bus will effectively disable missile explosions and explosive detonations in faction (and other grief protection plugins) land... provided they are chunk based (which most are).

See here: http://pastebin.com/nTwrPW2t

If you'd like to implement something please do and you've got my blessing to use this code haha :) 
If not, I'm covered.

**Comment by aidancbrady** [comment]
DefenseTech already ships with some helpful ExplosionEvents, you can see them in the API class. I've also just now integrated with block break events which should take care of most of the related issues.

**Comment by StargateMC** [comment]
@aidancbrady I know it does :) I used them to create a layer of compatibility between DT and Bukkit by firing vanilla forge events.

Bukkit plugins can't see them unless the forge event exists in vanilla forge with no mods.

Thanks for sorting it :)

**Comment by StargateMC** [comment]
One thing I did notice Aidan - if you cancel the earlier events in the explosion, it doesn't cancel future events.
Hence why I have null checks in my code above. Fires npes and crashes the server
