### ISSUE TITLE
Antimatter Bomb's recipe should use oreDict Antimatter

### ISSUE THREAD

**Issue by QuantumTraverse** [aidancbrady/DefenseTech#47]
DefenseTech is not looking for antimatter in the oreDict, so until it does, NuclearCraft's (or any other mod that adds antimatter) antimatter won't be usable in DefenseTech's recipes.

**Comment by aidancbrady** [comment]
Sadly, NuclearCraft antimatter is not registered in the ore dictionary. Regardless, I have plans to add support for antimatter in the future :)

**Comment by QuantumTraverse** [comment]
Don't worry, I've talked to both you and the author of NuclearCraft to
create support for Antimatter in the oreDictionary.
