### ISSUE TITLE
Multiple Missile Issues

### ISSUE THREAD

**Issue by QuantumTraverse** [aidancbrady/DefenseTech#49]
Issue 1: Even when using entirely T3 launching set, launching any tier of missile at a target in the air (such as a floating slime island from Tinkers' Construct) by any aiming means (including laser designators and the radar gun) will result in the missile missing its target by a significant amount, much more than the 0 block inaccuracy a full tier 3 system should have.

Issue 2: Anti-Ballistic Missiles miss the missile they are designed to take down almost every time I have tested it.

**Comment by aidancbrady** [comment]
I've fixed the issues with Anti-Ballistic Missiles.

As for your first issue, I'm not sure what to say- I'm unable to reproduce that. Make sure your launcher support frame is connected to the launcher base properly.

**Comment by QuantumTraverse** [comment]
I have recorded a video of the first phenomenon and placed it in a zip on [dropbox.](https://www.dropbox.com/s/yfqtr67ab8cth6g/Missile%20Test%20LQ.zip?dl=0)
