### ISSUE TITLE
missiles are exploding way short of thier range

### ISSUE THREAD

**Issue by mrgreaper** [aidancbrady/DefenseTech#51]
missiles seem to be exploding in the air miles from thier intended targets, shrapnel and contagous were tried
t3 launchers, platforms etc. 
fuel is set to false
max range is set to 10000 
we cant figure it out. 
The strange thing is im sure they were working fine the other day(though those were anti-ballistic misiles when we tested it before.

different launchers used same issue, they just explode mid air like they are hitting some sort of range.

**Comment by Henri2h** [comment]
I am facing the same issue

[13:33:54] [Server thread/ERROR] [FML]: The mod DefenseTech attempted to force load a chunk with an invalid ticket. This is not permitted.

**Comment by mrgreaper** [comment]
this happened for me with me actually riding the misiles, so the chunk loading shouldnt of been an issue (but this is minecraft, where logic is not always straight forward lol

**Comment by aidancbrady** [comment]
Should be fixed, I just found a pre-1.7.10 issue that carried over.  Let me know :)
