### ISSUE TITLE
Recommended version on aidancbrady.com is Old

### ISSUE THREAD

**Issue by QuantumTraverse** [aidancbrady/DefenseTech#53]
Recommended version is 1.0.1.26, despite the newest version being 1.0.1.46. Is that intentional, or have you just forgotten to change that?

**Comment by aidancbrady** [comment]
Intentional, as I'm still working to finish some more features until I recommend a new release. This being said, 1.0.0 is definitely more stable than the earlier releases.

**Comment by aidancbrady** [comment]
1.0.1, excuse me :)
