### ISSUE TITLE
Missiles getting lost on their way

### ISSUE THREAD

**Issue by LokeYourC3PH** [aidancbrady/DefenseTech#54]
So, Missiles have one HUGE problem: If the distance is any further than maybe 2 or 3 chunks that are not loaded, missiles end up getting lost over relatively large distances, like 300 blocks or more. The issue in that is, why have missiles, if they never arrive at their location anyway. I have found this issue in my modpack, and also in someone elses modpack that has a completely different setup, other than having DefenseTech. "We" are using the latest version of DefenseTech. The missiles just seem to get stuck mid air, waiting for you to chunkload them. The chunkloader for missiles either doesn't work, or is just too slow.

**Comment by henri2h** [comment]
Take a look at :

https://github.com/aidancbrady/DefenseTech/issues/51

I think that is the same issue

**Comment by LokeYourC3PH** [comment]
Well no, the missiles aren't exploding. You see, when i launch one where i sit ontop of the missile myself and fly away with it, the other missiles actually start up again and keep flying ahead of me, hitting the ground just some seconds before my missile also hits the ground. So they just get stuck on their way where there are no chunks loaded, and once they become loaded, they keep moving on.

**Comment by LemADEC** [comment]
Either the chunk-loading range is too small regarding the propagation speed,
Or the entity isn't ticking anymore as there's no players close enough (Spigot patch).
