### ISSUE TITLE
map corrupt with chemical missile in single player is shot

### ISSUE THREAD

**Issue by AndrewCraft-Server** [aidancbrady/DefenseTech#58]
the map corrupt's when chemical missile is shot from missile launcher with galacticraft installed.
[crash-2016-07-23_02.02.38-client.txt](https://github.com/aidancbrady/DefenseTech/files/379409/crash-2016-07-23_02.02.38-client.txt)

**Comment by aidancbrady** [comment]
Report this to GC.
