### ISSUE TITLE
Missile Misdetonation

### ISSUE THREAD

**Issue by Robot-Gentleman** [aidancbrady/DefenseTech#6]
If I fire an antimatter missile or nuclear cluster missile and then reload another of either type into either the same launcher or another launcher when the first missile impacts the one in the launcher explodes too. This means if I launch an antimatter it detonates all other nuclear cluster and antimatter missiles in launchers and the same happens if I launch a nuclear cluster. This also occurs when there is already either a nuclear cluster or antimatter loaded and not just if I load it during the flight of an antimatter/nuclear cluster. These are the only types of missiles this seems to happen with.

**Comment by aidancbrady** [comment]
Thanks.  This was actually once intended behavior I believe; the entity damage algorithm stretches out 2 times the radius, and it will blow up any missiles within that range.  I've changed the functionality to only damage entities within the radius of the explosive itself.

**Comment by Robot-Gentleman** [comment]
It didn't appear to fix the problem. I have updated to the 1.0.1.29 for 1.7.10 version and it still triggers from farther than the bomb

**Comment by aidancbrady** [comment]
Try build #30 and let me know.
