### ISSUE TITLE
server crashes on startup

### ISSUE THREAD

**Issue by Nervyalloy5** [aidancbrady/DefenseTech#74]
[crash-2017-01-01_22.50.40-server.txt](https://github.com/aidancbrady/DefenseTech/files/680365/crash-2017-01-01_22.50.40-server.txt)

**Comment by Topspeedboy21** [comment]
Do you have any more text to that crash report? If you haven't played Minecraft since, you should go into latest.log and paste it into here. Usually it says "ended in bad exit code 1" or something like that. If you have anymore text, I will gladly help you solve your problem @nervyalloy51

**Comment by DagrMine** [comment]
One of the older versions of defense tech crashed servers for some reason. Fixed now (it works on forge 1614 fyi)
It might have been because I was using cauldron but idk about nervy's problem :/
